name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x
          check-latest: true
      - name: Install dependencies
        run: |
          npm ci
      - name: Build project
        run: |
          npm run build
      - name: Test project
        run: |
          npm run test:unit
      - name: Lint project
        run: |
          npm run lint
